Models/About.cs
namespace SQ20.Net_Wee7_8_Task.Models
{
    public class About : BaseEntity
    {
        public string? Name { get; set; }
        public string? Description { get; set; }
    }
}

Controllers/AboutController.cs
using Microsoft.AspNetCore.Mvc;
using SQ20.Net_Wee7_8_Task.Data;
using SQ20.Net_Wee7_8_Task.Interface;
using SQ20.Net_Wee7_8_Task.Interfaces;
using SQ20.Net_Wee7_8_Task.Models;
using SQ20.Net_Wee7_8_Task.Repository;
using SQ20.Net_Wee7_8_Task.Services;
using SQ20.Net_Wee7_8_Task.ViewModels;

namespace SQ20.Net_Wee7_8_Task.Controllers
{
    public class AboutsController : Controller
    {
        private readonly IAboutRepository _aboutRepository;
        private readonly IPhotoService _photoService;
        private readonly IHttpContextAccessor _httpContextAccessor;

        public AboutsController(IAboutRepository aboutRepository, IPhotoService photoService, IHttpContextAccessor httpContextAccessor)
        {
            _aboutRepository = aboutRepository;
            _photoService = photoService;
            _httpContextAccessor = httpContextAccessor;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var abouts = await _aboutRepository.GetAll();
            return View(abouts);
        }

        public async Task<IActionResult> Edit(Guid Id)
        {
            var abouts = await _aboutRepository.GetByIdAsync(Id);
            if (abouts == null) return View("Error");
            var aboutVm = new EditAboutViewModel()
            {
                Name = abouts.Name,
                Description = abouts.Description

            };

            return View(aboutVm);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Guid Id, EditAboutViewModel aboutVm)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Failed To Edit About");
                View("Edit", aboutVm);
            }
            // TO BE USED LATER ON
            /*var result = await _photoService.AddPhotoAsync(aboutVm.Image);*/

            /*if (result.Error != null)
            {
                ModelState.AddModelError("Img", "Photo Failed To UPLOAD");
                return View("Edit", aboutVm);
            }*/

            var abouts = new About()
            {
                Id = Id,
                Name = aboutVm.Name,
                Description = aboutVm.Description,
                /*Image = result.Url.ToString(),*/

            };

            _aboutRepository.Update(abouts);
            return RedirectToAction("Index");

        }

    }

}

Controllers/EducationController.cs
using Microsoft.AspNetCore.Mvc;
using SQ20.Net_Wee7_8_Task.Interface;
using SQ20.Net_Wee7_8_Task.Interfaces;
using SQ20.Net_Wee7_8_Task.Models;
using SQ20.Net_Wee7_8_Task.Repository;
using SQ20.Net_Wee7_8_Task.ViewModels;

namespace SQ20.Net_Wee7_8_Task.Controllers
{
    public class EducationController : Controller
    {
        private readonly IEducationRepository _edRepository;
        private readonly IPhotoService _photoService;
        private readonly IHttpContextAccessor _httpContextAccessor;

        public EducationController(IEducationRepository edRepository, IPhotoService photoService, IHttpContextAccessor httpContextAccessor)
        {
            _edRepository = edRepository;
            _photoService = photoService;
            _httpContextAccessor = httpContextAccessor;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var educations = await _edRepository.GetAll();
            return View(educations);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateEducationViewModel edVm)
        {

            if (ModelState.IsValid)
            {
                /* var result = await _photoService.AddPhotoAsync(projectVm.Image);*/

                var education = new Education()
                {
                    Degree = edVm.Degree,
                    School = edVm.School,
                    GraduationDate = edVm.GraduationDate,
                };

                _edRepository.Add(education);
                return RedirectToAction("Index");

            }
            else
            {
                ModelState.AddModelError("", "Photo Upload Failed");
            }

            return View(edVm);
        }

        public async Task<IActionResult> Edit(Guid Id)
        {
            var educate = await _edRepository.GetByIdAsync(Id);
            if (educate == null) return View("Error");
            var edVm = new EditEducationViewModel()
            {
                Degree = educate.Degree,
                School = educate.School,
                GraduationDate = educate.GraduationDate,

            };

            return View(edVm);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Guid Id, EditEducationViewModel edVm)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Failed To Edit ED");
                View("Edit", edVm);
            }

            var educations = new Education()
            {
                Id = Id,
                School = edVm.School,
                Degree = edVm.Degree,
                GraduationDate = edVm.GraduationDate


            };

            _edRepository.Update(educations);
            return RedirectToAction("Index");

        }
    }
}

Controllers/ProjectController.cs
using Microsoft.AspNetCore.Mvc;
using SQ20.Net_Wee7_8_Task.Interfaces;
using SQ20.Net_Wee7_8_Task.Services;
using SQ20.Net_Wee7_8_Task.Models;
using SQ20.Net_Wee7_8_Task.ViewModels;
using SQ20.Net_Wee7_8_Task.Interface;

namespace SQ20.Net_Wee7_8_Task.Controllers
{
    public class ProjectController : Controller
    {
        private readonly IProjectRepository _projectRepository;
        private readonly IPhotoService _photoService;


        public ProjectController(IProjectRepository projectRepository, IPhotoService photoService)
        {
            _projectRepository = projectRepository;
            _photoService = photoService;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var projects = await _projectRepository.GetAll();
            return View(projects);
        }

        // work in progress
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreatePortfolioViewModel projectVm)
        {

            if (ModelState.IsValid)
            {
                var result = await _photoService.AddPhotoAsync(projectVm.Image);

                var project = new Portfolio()
                {
                    Title = projectVm.Title,
                    Description = projectVm.Description,
                    Image = result.Url.ToString(),
                };

                _projectRepository.Add(project);
                return RedirectToAction("Index");

            }
            else
            {
                ModelState.AddModelError("", "Photo Upload Failed");
            }

            return View(projectVm);
        }



        //
        [HttpGet]
        public async Task<IActionResult> Edit(Guid Id)
        {
            var projects = await _projectRepository.GetByIdAsync(Id);
            if (projects == null) return View("Error");
            var projectVM = new EditProjectViewModel()
            {
                Title = projects.Title,
                Description = projects.Description

            };

            return View(projectVM);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Guid Id, EditProjectViewModel projectVm)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Failed To Edit Club");
                View("Edit", projectVm);
            }

            var result = await _photoService.AddPhotoAsync(projectVm.Image);

            if (result.Error != null)
            {
                ModelState.AddModelError("Img", "Photo Failed To UPLOAD");
                return View("Edit", projectVm);
            }

            var projects = new Portfolio()
            {
                Id = Id,
                Title = projectVm.Title,
                Description = projectVm.Description,
                Image = result.Url.ToString(),

            };

            _projectRepository.Update(projects);
            return RedirectToAction("Index");

        }

    }
}

Controllers/ServiceController.cs
using Microsoft.AspNetCore.Mvc;
using SQ20.Net_Wee7_8_Task.Interface;
using SQ20.Net_Wee7_8_Task.Models;
using SQ20.Net_Wee7_8_Task.ViewModel;
using SQ20.Net_Wee7_8_Task.ViewModels;

namespace SQ20.Net_Wee7_8_Task.Controllers
{
    public class ServiceController : Controller
    {
        private readonly IServiceRepository _serviceRepository;
        private readonly IPhotoService _photoService;


        public ServiceController(IServiceRepository serviceRepository, IPhotoService photoService)
        {
            _serviceRepository = serviceRepository;
            _photoService = photoService;
        }


        public async Task<IActionResult> Index()
        {
            var services = await _serviceRepository.GetAll();
            return View(services);
        }

        //
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateProjectViewModel serviceVm)
        {
            //return View();
            //this means thta if the user did not input a required field,this will show the user
            //the error while still on that page depending on the field not filled in correctly
            if (ModelState.IsValid)
            {
                var result = await _photoService.AddPhotoAsync(serviceVm.Image);

                var service = new Service()
                {
                    Title = serviceVm.Title,
                    Description = serviceVm.Description,
                    Image = result.Url.ToString(),
                };

                _serviceRepository.Add(service);
                return RedirectToAction("Index");

            }
            else
            {
                ModelState.AddModelError("", "Photo Upload Failed");
            }

            return View(serviceVm);
        }


        //

        [HttpGet]
        public async Task<IActionResult> Edit(Guid Id)
        {
            var services = await _serviceRepository.GetByIdAsync(Id);
            if (services == null) return View("Error");
            var serviceVM = new EditServicesViewModel()
            {
                Title = services.Title,
                Description = services.Description
            };

            return View(serviceVM);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Guid Id, EditServicesViewModel serviceVM)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Failed To Edit Club");
                View("Edit", serviceVM);
            }

            var result = await _photoService.AddPhotoAsync(serviceVM.Image);

            if (result.Error != null)
            {
                ModelState.AddModelError("Img", "Photo Failed To UPLOAD");
                return View("Edit", serviceVM);
            }

            var services = new Service()
            {
                Id = Id,
                Title = serviceVM.Title,
                Description = serviceVM.Description,
                Image = result.Url.ToString(),

            };

            _serviceRepository.Update(services);
            return RedirectToAction("Index");

        }

    }
}

Controllers/SkillController.cs
using Microsoft.AspNetCore.Mvc;
using SQ20.Net_Wee7_8_Task.Interface;
using SQ20.Net_Wee7_8_Task.Interfaces;
using SQ20.Net_Wee7_8_Task.Models;
using SQ20.Net_Wee7_8_Task.Repository;
using SQ20.Net_Wee7_8_Task.ViewModels;

namespace SQ20.Net_Wee7_8_Task.Controllers
{
    public class SkillController : Controller
    {
        private readonly ISkillRepository _skillRepository;
        private readonly IPhotoService _photoService;

        public SkillController(ISkillRepository skillRepository, IPhotoService photoService)
        {
            _skillRepository = skillRepository;
            _photoService = photoService;

        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var skills = await _skillRepository.GetAll();
            return View(skills);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateSkillViewModel skillVm)
        {

            if (ModelState.IsValid)
            {
                /* var result = await _photoService.AddPhotoAsync(projectVm.Image);*/

                var skill = new Skill()
                {
                    Name = skillVm.Name,
                    Description = skillVm.Description
                    /* Image = result.Url.ToString(),*/
                };

                _skillRepository.Add(skill);
                return RedirectToAction("Index");

            }
            else
            {
                ModelState.AddModelError("", "Photo Upload Failed");
            }

            return View(skillVm);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(Guid Id)
        {
            var skill = await _skillRepository.GetByIdAsync(Id);
            if (skill == null) return View("Error");
            var skillVM = new EditSkillViewModel()
            {
                Name = skill.Name,
                Description = skill.Description

            };

            return View(skillVM);
        }


        [HttpPost]
        public async Task<IActionResult> Edit(Guid Id, EditSkillViewModel skillVm)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Failed To Edit About");
                View("Edit", skillVm);
            }

            var skill = new Skill()
            {
                Id = Id,
                Name = skillVm.Name,
                Description = skillVm.Description,
                /*Image = result.Url.ToString(),*/

            };

            _skillRepository.Update(skill);
            return RedirectToAction("Index");

        }
    }
}

Views/About/Edit.cshtml
@using Microsoft.AspNetCore.Mvc.TagHelpers
@model SQ20.Net_Wee7_8_Task.ViewModels.EditAboutViewModel


<form method="post" asp-action="Edit" enctype="multipart/form-data" class="editParent">
    <input type="hidden" value="Id" id="Id" />
    <div class="form-group editPage">
        <label asp-for="Name">Title</label>
        <input asp-for="Name" class="form-control" placeholder="Title">
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div class="form-group  editPage">
        <label asp-for="Description">Description</label>
        <input asp-for="Description" class="form-control" placeholder="Description">
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>
    @* <div class="form-group  editPage">
    <label asp-for="Image">Image</label>
    <input asp-for="Image" type="file" class="form-control" placeholder="Image">
    <span asp-validation-for="Image" class="text-danger"></span>


    <div class="form-group">
    <label asp-for="ClubCategory">Club Category</label>
    <select asp-for="ClubCategory" asp-items="@Html.GetEnumSelectList<ClubCategory>()" class="form-control">
    <option selected="selected" value="">--Select--</option>
    </select>
    <span asp-validation-for="ClubCategory" class="text-danger"></span>
    </div>

    </div> *@
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

Views/About/Index.cshtml
@model IEnumerable<About>

@{
    Layout = "_DashboardLayout.cshtml";
    ViewData["Title"] = "About";
    
}

<div class="container">
    <!-- Navigation Section -->
    <div class="navigation">
        <ul>
            <li>
                <a href="#">
                    <span class="icon">
                        <ion-icon name="logo-apple"></ion-icon>
                    </span>
                    <span class="title">My Dashboard</span>
                </a>
            </li>
            <li>
                <a asp-controller="Service" asp-action="Index">
                    <span class="icon">
                        <ion-icon name="home-outline"></ion-icon>
                    </span>
                    <span class="title">Services</span>
                </a>
            </li>
            <li>
                <a asp-controller="Project" asp-action="Index">
                    <span class="icon">
                        <ion-icon name="people-outline"></ion-icon>
                    </span>
                    <span class="title">Portfolio</span>
                </a>
            </li>
            <li>
                <a asp-controller="Abouts" asp-action="Index">
                    <span class="icon">
                        <ion-icon name="chatbubble-outline"></ion-icon>
                    </span>
                    <span class="title">About</span>
                </a>
            </li>
            <li>
                <a asp-controller="Skill" asp-action="Index">
                    <span class="icon">
                        <ion-icon name="help-outline"></ion-icon>
                    </span>
                    <span class="title">Skill</span>
                </a>
            </li>
            <li>
                <a asp-controller="Education" asp-action="Index">
                    <span class="icon">
                        <ion-icon name="settings-outline"></ion-icon>
                    </span>
                    <span class="title">Education</span>
                </a>
            </li>
            <li>
                <a asp-controller="Experience" asp-action="Index">
                    <span class="icon">
                        <ion-icon name="lock-closed-outline"></ion-icon>
                    </span>
                    <span class="title">Experience</span>
                </a>
            </li>
            <li>
                <a asp-controller="Home" asp-action="Index">
                    <span class="icon">
                        <ion-icon name="log-out-outline"></ion-icon>
                    </span>
                    <span class="title">Log Out</span>
                </a>
            </li>
        </ul>
    </div>
    <!-- Main Section -->
    <div class="main">
        <div class="topbar">
            <div class="toggle">
                <ion-icon name="menu-outline"></ion-icon>
            </div>
            <!-- Search -->
            <div class="search">
                <label>
                    <input type="text" name="search" placeholder="Search Here...">
                    <ion-icon name="search-outline"></ion-icon>
                </label>
            </div>
            <!-- User Account -->
            <div class="user">
                <img src="img/user/user.jpg" alt="user image">
            </div>
            <div class="accountMenu">
                <h3>Noha Fawzy<br /><span>Entrepreneur</span></h3>
                <ul>
                    <li>
                        <img src="img/user/user.png" alt="profile">
                        <a href="#">My Profile</a>
                    </li>
                    <li>
                        <img src="img/user/edit.png" alt="profile">
                        <a href="#">Edit Profile</a>
                    </li>
                    <li>
                        <img src="img/user/envelope.png" alt="profile">
                        <a href="#">Inbox</a>
                    </li>
                    <li>
                        <img src="img/user/settings.png" alt="profile">
                        <a href="#">Settings</a>
                    </li>
                    <li>
                        <img src="img/user/question.png" alt="profile">
                        <a href="#">Help</a>
                    </li>
                    <li>
                        <img src="img/user/log-out.png" alt="profile">
                        <a asp-controller="Home" asp-action="Index">Log Out</a>
                    </li>
                </ul>
            </div>
        </div>
        <!-- Cards -->
        <!-- Charts -->
        <section class="portfolio" id="portfolio">
            <div class="center-text">
                <h2>About <span>ME</span></h2>
            </div>
            <div class="top-btnn">
            </div>
            @foreach (var items in Model)
            {
                <div class="Portfolio-content">
                    <div class="row">

                        <div class="main-row">
                            <div class="row-text">
                                <h5>@items.Name</h5>

                            </div>
                            <div class="row-icon">
                                <i class="ri-github-fill"></i>
                            </div>
                        </div>
                        <h4>@items.Description</h4>
                    </div>
                    <div class="top-btnn">
                        <a asp-controller="Abouts" asp-action="Edit" asp-route-Id="@items.Id" class="h-btn1">Edit</a>
                    </div>

                </div>

            }

        </section>

    </div>
</div>

@* <section class="portfolio" id="portfolio">
    <div class="center-text">
        <h2>About <span>ME</span></h2>
    </div>
    <div class="top-btnn">

    </div>
    @foreach (var items in Model)
    {
        <div class="Portfolio-content">
            <div class="row">

                <div class="main-row">
                    <div class="row-text">
                        <h5>@items.Name</h5>

                    </div>
                    <div class="row-icon">
                        <i class="ri-github-fill"></i>
                    </div>
                </div>
                <h4>@items.Description</h4>
            </div>
            <div class="top-btnn">
                <a asp-controller="Abouts" asp-action="Edit" asp-route-Id="@items.Id" class="h-btn1">Edit</a>
            </div>

        </div>

    }

</section> *@